#!/bin/bash

python3 "$1" "${@:1:}" 2>&1 | tee log.txt

# Check if there was an error
if [ ${PIPESTATUS[0]} -ne 0 ]
    then

    # Ask if they want to commit
    echo
    read -p $'\e[1;36mWould you like to commit: ' SHOULD_COMMIT

    # If so
    if [[ $SHOULD_COMMIT == y* ]]
    then
        # Get their commit message
        read -p $'\e[1;36mEnter a commit message: ' COMMIT_MESSAGE
        COMMIT_MESSAGE="${COMMIT_MESSAGE:0:72}"

        # Default to the date/time if they don't give a message
        MSG=${COMMIT_MESSAGE:=$(date +"%D %T")}

        # And then commit
        git add .
        git commit -m "$MSG"
    fi
fi

# git show 1904f9dd0b967af1675c099c02bf6a6270d6f346:script.py