#!/bin/bash

python3 "$1" "${@:1:}" 2>&1 | tee log.txt

# Check if there was an error
if [ ${PIPESTATUS[0]} -ne 0 ]
    then
        # Ask if they want to commit
        echo
        read -p $'\e[1;31mThere was a non-zero exit. Would you like to commit: \e[0m' SHOULD_COMMIT
    else
        # Ask if they want to commit
        echo
        read -p $'\e[1;36mWould you like to commit: \e[0m' SHOULD_COMMIT
fi
    
# If so
if [[ $SHOULD_COMMIT == y* ]]
    then
        # Get their commit message
        read -p $'\e[1;32mEnter a commit message: \e[0m' COMMIT_MESSAGE
        COMMIT_MESSAGE="${COMMIT_MESSAGE:0:72}"

        # Default to the date/time if they don't give a message
        MSG=${COMMIT_MESSAGE:=$(date +"%D %T")}

        # And then commit
        git add .
        git commit -m "$MSG"
        git push
fi
